### ISSUE TITLE
How to run eventyay-talk locally

### ISSUE THREAD

**Issue by ajutamangdev** [fossasia/eventyay-talk#246]
I am trying to build this locally using python virtual environment setup.
Things I have proceed for the setup
- installed the python environment and virtualenv
- setup the virtualenv and activated to install the packages of the eventyay-talk

```
git clone https://github.com/fossasia/eventyay-talk
cd eventyay-talk
virtualenv env
source env/bin/activate
pip install -e .
```

Till this I was able to install packages successfully. Based on the installed packages, this project runs the django. I tried to run the django server locally but couldn't proceed.

```
cd src
python3 manage.py runserver
```

Here is the error logs.
```
python3 manage.py server
Traceback (most recent call last):
  File "/home/eventyay-talk/env/lib/python3.12/site-packages/django/core/management/__init__.py", line 255, in fetch_command
    app_name = commands[subcommand]
               ~~~~~~~~^^^^^^^^^^^^
KeyError: 'server'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eventyay-talk/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/opensource/eventyay-talk/env/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/eventyay-talk/env/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eventyay-talk/env/lib/python3.12/site-packages/django/core/management/__init__.py", line 262, in fetch_command
    settings.INSTALLED_APPS
  File "/home/eventyay-talk/env/lib/python3.12/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/home/eventyay-talk/env/lib/python3.12/site-packages/django/conf/__init__.py", line 68, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eventyay-talk/env/lib/python3.12/site-packages/django/conf/__init__.py", line 166, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/eventyay-talk/src/pretalx/settings.py", line 11, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'

```

Are there any missing configuration we have to configure before running the server locally ? Also I found the i wasn't able to run the sphinx documentation of the docs folder. cc @mariobehling

**Comment by Ammar-Munirr** [comment]
I have fix this on my local machine by just installing this tool within the environment `pip install setuptools`

![Screenshot from 2024-12-16 12-41-27](https://github.com/user-attachments/assets/ed7928eb-92db-4728-8e25-de700a8cf95e)

**Comment by ARYPROGRAMMER** [comment]
@ajutamangdev run 
```sh
pip install -e .
```
in the root and then 

```sh
cd src/
python manage.py [optional - runserver]
```

**Comment by harshitrwt** [comment]
Hi @ARYPROGRAMMER ,  
These commands worked for me 

<pre>git clone https://github.com/fossasia/eventyay-talk
cd eventyay-talk
python -m venv env
.\env\Scripts\activate
pip install -e .

cd src
python manage.py migrate
python manage.py runserver  </pre>

The server starts successfully and opens up on localhost, but I encountered a problem while attempting to log in. Could you please provide guidance on the recommended authentication setup for local development?


![Image1](https://github.com/user-attachments/assets/3971ce15-18ce-42e6-aed1-e686a3b90428)

![Image2](https://github.com/user-attachments/assets/b4ca94ad-cdc6-42d3-bf7b-794628ed09bf)

Additionally, I believe a CONTRIBUTING.md file should be added to the repository. This file can outline the full setup process for running the project locally, which would greatly improve the onboarding experience for new contributors. How about creating a dedicated issue for this enhancement if one doesn’t already exist.
